### ISSUE TITLE
Vortex Node Bug- Found 11/24/2020

### ISSUE THREAD

**Issue by DesiredBreakfast** [Lord-of-the-Craft/tracker#21]
MC Names of all involved
Kholibrii
Description
After the Tin ore respawns it says the "mined" texture(bedrock), despite the fact it has regenerated and can be harvested.
Date of occurrence
11/24/2020
In-game specifications
It seems to be only related to Tin nodes(That I've seen) and occurred at both tin clusters at spawn
Steps to Reproduce

Step 1: Mine the Tin Node
Step 2: Wait the required time for it to regenerate
Step 3: See the node still has the "mined" texture
Step 4: Attempt to mine it and still be successful in receiving the material, despite the texture
Expected Behavior
After the required time for the node to regenerate for it to return to the "unmined" texture
Actual Behavior
After the required time for the note to regenerate it does not return to its "unmined" texture and retains the "mined" texture while still being able to be harvested
Additional Information
The issue could possibly be that you are able to harvest it while it is still on cooldown, but I doubt it based on the fact I waited nearly 45 minutes for the notes to regen before trying to mine the "mined" texture and receiving the resource. 
Error Message
N/A

**Comment by Nickrocky** [comment]
After poking around in the code I figured out a way to replicate this behavior though it only seems to happen with /plugman reloading Vortex, this only occured back in 0.1.0. This bug was fixed back in January, and since then even with plugman I cant seem to replicate the issue on 1.0.0. Consider it resolved with the 1.0.0 patch
