### ISSUE TITLE
Player tagged as a Wandering Soul

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#247]
**Issue**
A player seems to have been bugged into being a wandering soul. I believe this is known, but could not find an actual issue on the tracker for it.

Able to open doors and punch people still.

They stated that they had just come online to vote when they noticed, but did not have issues the previous day. Possibly connected to /vote milestone or #219 ?

![image](https://user-images.githubusercontent.com/48634310/157120767-893ae23b-9209-42a2-846f-11c706499949.png)
![image](https://user-images.githubusercontent.com/48634310/157120955-8f59a52c-290e-439e-8849-caa835439c94.png)

**Ticket refence number:**
RTS-
![image](https://user-images.githubusercontent.com/48634310/157120720-5c97ae58-9695-486f-ac01-a28a83a50afe.png)

**Comment by polysemic-mc** [comment]
For additional info:
Group `group.default` is added to the player by some plugin, and `group.normal` is removed. Unsure why this is happening, can be fixed by having someone go into LP editor and removing/adding the groups manually.

Issue started somewhere 4-5 months ago, if my memory serves me right. Might be Freja or some other plugin that edits the perms. If those things get logged, might be able to find it there - assuming that the thing that changes it is also kept in the logs @Kowaman @CommissarVoop
